AWSTemplateFormatVersion: "2010-09-09"
Description: Docker CodePipeline with Cloudformation 

Parameters:
  PipeLineName:
    Type: String
    Default: default-docker-pipeline
  ConfigurationOwner:
    Type: String
    Default: Axit88
  Repo:
    Type: String
    Default: ecs-python
  Branch:
    Type: String
    Default: main
  OAuthToken:
    Type: String
    Default: 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
  BucketName:
    Type: String
    Default: axitsamplepipelinebucket
  DockerCodePipelineRoleName: 
    Type: String
    Default: nested-DockerCodePipeline-role
  IAMRoleForDockerCodeBuildName:
    Type: String
    Default: nested-IAMRoleForDockerCodeBuild
  IAMRoleForDeployDockerCodePipelineName:
    Type: String
    Default: nested-IAMRoleForDeployDockerCodePipeline
  BuildType: 
    Type: String
    Default: LINUX_CONTAINER
  BuildImage:
    Type: String
    Default: aws/codebuild/amazonlinux2-x86_64-standard:4.0
  BuildComputeType: 
    Type: String
    Default: BUILD_GENERAL1_SMALL
  EcsClusterName: 
    Type: String
    Default: ec2Cluster
  EcsServiceName: 
    Type: String
    Default: pythonAppService2
    
Resources:
  DockerCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref BucketName
      Name: !Ref PipeLineName
      RestartExecutionOnUpdate: true 
      RoleArn: !GetAtt IAMRoleForDockerCodePipeline.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: "1"
                Provider: GitHub
              Configuration:
                Owner: !Ref ConfigurationOwner
                Repo: !Ref Repo
                Branch: !Ref Branch
                OAuthToken: !Ref OAuthToken
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref BuildProject
              RunOrder: 1

        - Name: Dev
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: ECS
              Configuration:
                ClusterName: Devecs-cluster 
                ServiceName: Devecs-service
                FileName: DevImagedefinitions.json
              InputArtifacts: 
                - Name: BuildOutput
              RunOrder: 1
        
        - Name: Qa
          Actions:
            - Name: Approval
              RunOrder: 1
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: Approve or Reject this change 
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: ECS
              Configuration:
                ClusterName: Qaecs-cluster 
                ServiceName: Qaecs-service
                FileName: QaImagedefinitions.json
              InputArtifacts: 
                - Name: BuildOutput
              RunOrder: 2

        - Name: Prod
          Actions:
            - Name: Approval
              RunOrder: 1
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: Approve or Reject this change 
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: ECS
              Configuration:
                ClusterName: Prodecs-cluster 
                ServiceName: Prodecs-service
                FileName: ProdImagedefinitions.json
              InputArtifacts: 
                - Name: BuildOutput
              RunOrder: 2

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: dockerBuildProject
      Source:
        Type: GITHUB
        Location: !Sub 'https://github.com/${ConfigurationOwner}/${Repo}.git'
      Artifacts:
        Type: S3 
        Name: BuildProjectArtifacts
        Location: !Ref BucketName
      Triggers:
        Webhook: true
      Environment:
        Type: !Ref BuildType
        Image: !Ref BuildImage
        ComputeType: !Ref BuildComputeType
        ImagePullCredentialsType: CODEBUILD 
        PrivilegedMode: true 
      ServiceRole: !GetAtt IAMRoleForDockerCodeBuild.Arn
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      Tags:
        - Key: env 
          Value: integration 
        - Key: application 
          Value: dockercodepipeline  
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED

  DockerPipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref OAuthToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: !Sub refs/heads/main
      TargetAction: Source 
      TargetPipeline: !Ref DockerCodePipeline
      TargetPipelineVersion: !GetAtt DockerCodePipeline.Version
      RegisterWithThirdParty: 'true' 
  
  IAMRoleForDockerCodePipeline:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      RoleName: !Ref DockerCodePipelineRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Tags:
        - Key: env 
          Value: integration 
        - Key: application 
          Value: dockercodepipeline 
      Policies:
        - PolicyName: DockerCodePipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Action:
              - iam:PassRole
              Resource: "*"
              Effect: Allow
              Condition:
                StringEqualsIfExists:
                  iam:PassedToService:
                  - cloudformation.amazonaws.com
                  - elasticbeanstalk.amazonaws.com
                  - ec2.amazonaws.com
                  - ecs-tasks.amazonaws.com
            - Action:
              - codecommit:CancelUploadArchive
              - codecommit:GetBranch
              - codecommit:GetCommit
              - codecommit:GetRepository
              - codecommit:GetUploadArchiveStatus
              - codecommit:UploadArchive
              Resource: "*"
              Effect: Allow
            - Action:
              - codedeploy:CreateDeployment
              - codedeploy:GetApplication
              - codedeploy:GetApplicationRevision
              - codedeploy:GetDeployment
              - codedeploy:GetDeploymentConfig
              - codedeploy:RegisterApplicationRevision
              Resource: "*"
              Effect: Allow
            - Action:
              - codestar-connections:UseConnection
              Resource: "*"
              Effect: Allow
            - Action:
              - elasticbeanstalk:*
              - ec2:*
              - elasticloadbalancing:*
              - autoscaling:*
              - cloudwatch:*
              - s3:*
              - sns:*
              - cloudformation:*
              - rds:*
              - sqs:*
              - ecs:*
              Resource: "*"
              Effect: Allow
            - Action:
              - lambda:InvokeFunction
              - lambda:ListFunctions
              Resource: "*"
              Effect: Allow
            - Action:
              - opsworks:CreateDeployment
              - opsworks:DescribeApps
              - opsworks:DescribeCommands
              - opsworks:DescribeDeployments
              - opsworks:DescribeInstances
              - opsworks:DescribeStacks
              - opsworks:UpdateApp
              - opsworks:UpdateStack
              Resource: "*"
              Effect: Allow
            - Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:SetStackPolicy
              - cloudformation:ValidateTemplate
              Resource: "*"
              Effect: Allow
            - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:BatchGetBuildBatches
              - codebuild:StartBuildBatch
              Resource: "*"
              Effect: Allow
            - Effect: Allow
              Action:
              - devicefarm:ListProjects
              - devicefarm:ListDevicePools
              - devicefarm:GetRun
              - devicefarm:GetUpload
              - devicefarm:CreateUpload
              - devicefarm:ScheduleRun
              Resource: "*"
            - Effect: Allow
              Action:
              - servicecatalog:ListProvisioningArtifacts
              - servicecatalog:CreateProvisioningArtifact
              - servicecatalog:DescribeProvisioningArtifact
              - servicecatalog:DeleteProvisioningArtifact
              - servicecatalog:UpdateProduct
              Resource: "*"
            - Effect: Allow
              Action:
              - cloudformation:ValidateTemplate
              Resource: "*"
            - Effect: Allow
              Action:
              - ecr:DescribeImages
              Resource: "*"
            - Effect: Allow
              Action:
              - states:DescribeExecution
              - states:DescribeStateMachine
              - states:StartExecution
              Resource: "*"
            - Effect: Allow
              Action:
              - appconfig:StartDeployment
              - appconfig:StopDeployment
              - appconfig:GetDeployment
              Resource: "*" 

  IAMRoleForDockerCodeBuild:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      RoleName: !Ref IAMRoleForDockerCodeBuildName
      Tags:
        - Key: env 
          Value: integration 
        - Key: application 
          Value: dockercodepipeline 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
      Policies:
        - PolicyName: DockerCodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Action:
              - ecr:*
              Resource: "*"
              Effect: Allow

Outputs:
  DockerCodePipeline:
    Description: DockerCodePipeline Detail
    Value: !Ref DockerCodePipeline
    Export:
      Name: DockerCodePipeline
  
# aws cloudformation create-stack --stack-name pipelineDocker --template-body file://pipeline.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback

# aws cloudformation update-stack --stack-name pipelineDocker --template-body file://pipeline.yaml --capabilities CAPABILITY_NAMED_IAM --disable-rollback
